# Generated by Django 3.2.8 on 2022-08-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='exit_coordinates',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maze',
            name='max_path',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='maze',
            name='min_path',
            field=models.JSONField(null=True),
        ),
    ]
