# Generated by Django 3.2.8 on 2022-08-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazes', '0002_auto_20220816_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maze',
            name='exit_coordinates',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maze',
            name='max_path',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maze',
            name='min_path',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
